package com.hackpuntes.fridagate.utils

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.net.InetSocketAddress
import java.net.Socket

/**
 * ProxyUtils - All logic related to routing Android traffic through Burp Suite.
 *
 * Burp Suite is a security tool that acts as an HTTP/HTTPS proxy, allowing
 * security researchers to intercept and inspect app network traffic.
 *
 * This utility provides two methods to redirect traffic:
 *
 * 1. System Proxy (no root required):
 *    Sets Android's global HTTP proxy setting.
 *    Only works for apps that respect the system proxy — many apps ignore it.
 *    Command: settings put global http_proxy IP:PORT
 *
 * 2. iptables Transparent Proxy (root required, recommended):
 *    Uses Linux firewall rules to redirect ALL TCP traffic on ports 80/443
 *    to Burp Suite, regardless of whether the app respects the system proxy.
 *    This captures traffic from apps that try to bypass proxy settings.
 *
 * Certificate Installation:
 *    For HTTPS traffic, Burp Suite uses its own SSL certificate to decrypt
 *    the connection. Android apps will reject this certificate by default.
 *    Installing Burp's CA certificate into the system trust store (requires root)
 *    makes Android trust Burp's certificate for all apps.
 */
object ProxyUtils {

    // -------------------------------------------------------------------------
    // iptables Transparent Proxy (root required)
    // -------------------------------------------------------------------------

    /**
     * Enables transparent proxy by adding iptables NAT rules.
     *
     * How iptables NAT works:
     *  - NAT = Network Address Translation
     *  - OUTPUT chain: rules applied to packets generated by this device
     *  - DNAT = Destination NAT: rewrites the destination address of packets
     *  - POSTROUTING + MASQUERADE: makes the rewritten packets look like they
     *    originate from this device (needed for DNAT to work in local routing)
     *
     * After these rules are active, any app trying to connect to port 80 or 443
     * will have its traffic silently redirected to Burp Suite instead.
     *
     * @param burpIp   The IP address of the machine running Burp Suite (e.g., "192.168.1.100")
     * @param httpPort The Burp listener port for HTTP traffic (typically 8080)
     * @param httpsPort The Burp listener port for HTTPS traffic (typically 8443)
     * @return true if the rules were applied successfully
     */
    suspend fun enableIptablesProxy(
        burpIp: String,
        httpPort: Int,
        httpsPort: Int
    ): Boolean = withContext(Dispatchers.IO) {
        // Never redirect device traffic to a listener that cannot be reached.
        if (!burpIp.matches(Regex("(?:[0-9]{1,3}\\.){3}[0-9]{1,3}")) ||
            burpIp.split(".").any { (it.toIntOrNull() ?: 256) !in 0..255 } ||
            httpPort !in 1..65535 || httpsPort !in 1..65535 ||
            !isBurpReachable(burpIp, httpPort)) {
            return@withContext false
        }

        try {
            // Use a dedicated chain. Never flush Android's shared OUTPUT or
            // POSTROUTING chains, which can contain rules owned by other apps.
            val command = """
                iptables -t nat -N FRIDAGATE_PROXY 2>/dev/null || true
                iptables -t nat -F FRIDAGATE_PROXY &&
                (iptables -t nat -C OUTPUT -j FRIDAGATE_PROXY 2>/dev/null || iptables -t nat -I OUTPUT 1 -j FRIDAGATE_PROXY) &&
                iptables -t nat -A FRIDAGATE_PROXY -p tcp --dport 80 -j DNAT --to-destination $burpIp:$httpPort &&
                iptables -t nat -A FRIDAGATE_PROXY -p tcp --dport 443 -j DNAT --to-destination $burpIp:$httpsPort &&
                echo FRIDAGATE_PROXY_SETUP_OK
            """.trimIndent()
            val result = RootUtils.executeSuCommand(command)
            result.contains("FRIDAGATE_PROXY_SETUP_OK") && isIptablesProxyEnabled()
        } catch (_: Exception) {
            false
        }
    }

    /**
     * Removes only FridaGate's dedicated chain and known legacy rules created by
     * older versions. It deliberately does not flush shared Android NAT chains.
     */
    suspend fun disableIptablesProxy(
        burpIp: String? = null,
        httpPort: Int? = null,
        httpsPort: Int? = null
    ): Boolean = withContext(Dispatchers.IO) {
        try {
            val legacyCleanup = if (
                burpIp != null &&
                burpIp.matches(Regex("(?:[0-9]{1,3}\\.){3}[0-9]{1,3}")) &&
                burpIp.split(".").all { (it.toIntOrNull() ?: 256) in 0..255 } &&
                httpPort != null && httpPort in 1..65535 && httpsPort != null && httpsPort in 1..65535
            ) {
                """
                while iptables -t nat -D OUTPUT -p tcp --dport 80 -j DNAT --to-destination $burpIp:$httpPort 2>/dev/null; do :; done
                while iptables -t nat -D OUTPUT -p tcp --dport 443 -j DNAT --to-destination $burpIp:$httpsPort 2>/dev/null; do :; done
                """.trimIndent()
            } else ""

            RootUtils.executeSuCommand(
                """
                iptables -t nat -D OUTPUT -j FRIDAGATE_PROXY 2>/dev/null || true
                iptables -t nat -F FRIDAGATE_PROXY 2>/dev/null || true
                iptables -t nat -X FRIDAGATE_PROXY 2>/dev/null || true
                $legacyCleanup
                echo FRIDAGATE_PROXY_CLEANUP_DONE
                """.trimIndent()
            )
            !isIptablesProxyEnabled()
        } catch (_: Exception) {
            false
        }
    }

    /**
     * Returns true when FridaGate's own proxy chain or legacy redirect rules exist.
     */
    suspend fun isIptablesProxyEnabled(): Boolean = withContext(Dispatchers.IO) {
        try {
            val ownChain = RootUtils.executeSuCommand("iptables -t nat -S FRIDAGATE_PROXY")
            if (ownChain.contains("--dport 80") || ownChain.contains("--dport 443")) return@withContext true
            val outputRules = RootUtils.executeSuCommand("iptables -t nat -S OUTPUT")
            outputRules.contains("-j FRIDAGATE_PROXY")
        } catch (_: Exception) {
            false
        }
    }

    // -------------------------------------------------------------------------
    // System Proxy (works without root, but limited coverage)
    // -------------------------------------------------------------------------

    /**
     * Sets the Android system-wide HTTP proxy.
     *
     * This uses the "settings" command to write to Android's global settings database.
     * Apps that are built to respect the system proxy (e.g., Chrome, most browsers)
     * will automatically route their traffic through this proxy.
     *
     * Note: Many apps explicitly disable proxy support to prevent interception.
     * For those apps, use the iptables method instead.
     *
     * @param ip   The proxy IP address (e.g., "192.168.1.100")
     * @param port The proxy port (e.g., 8080)
     * @return true if the setting was applied
     */
    suspend fun setSystemProxy(ip: String, port: Int): Boolean {
        return withContext(Dispatchers.IO) {
            try {
                // "settings put global" writes to Android's global settings
                // This is equivalent to going to WiFi settings and entering a proxy manually
                RootUtils.executeSuCommand("settings put global http_proxy $ip:$port")
                true
            } catch (e: Exception) {
                false
            }
        }
    }

    /**
     * Removes the Android system-wide HTTP proxy setting.
     *
     * Uses ":0" as the value to clear the proxy, then deletes the setting entirely.
     * Both steps are needed because some Android versions behave differently.
     *
     * @return true if the proxy was cleared
     */
    suspend fun clearSystemProxy(): Boolean {
        return withContext(Dispatchers.IO) {
            try {
                // http_proxy: legacy setting, some Android versions use this
                RootUtils.executeSuCommand("settings put global http_proxy :0")
                RootUtils.executeSuCommand("settings delete global http_proxy")
                // global_http_proxy: the actual effective system proxy on Android 8+,
                // persists across reboots — must be cleared or the WiFi "X" stays even after reboot
                RootUtils.executeSuCommand("settings put global global_http_proxy :0")
                RootUtils.executeSuCommand("settings delete global global_http_proxy")
                true
            } catch (e: Exception) {
                false
            }
        }
    }

    /**
     * Reads the current system proxy setting.
     *
     * @return The proxy string "IP:PORT" if set, null if no proxy is configured
     */
    suspend fun getSystemProxy(): String? {
        return withContext(Dispatchers.IO) {
            try {
                val legacy = RootUtils.executeSuCommand("settings get global http_proxy").trim()
                val modern = RootUtils.executeSuCommand("settings get global global_http_proxy").trim()
                // Prefer the modern global value when present; some Android builds keep
                // one key populated after the other has been cleared.
                val result = listOf(modern, legacy).firstOrNull {
                    it.isNotBlank() && it != "null" && it != ":0"
                }
                result
            } catch (e: Exception) {
                null
            }
        }
    }

    // -------------------------------------------------------------------------
    // Connectivity check
    // -------------------------------------------------------------------------

    /**
     * Tests whether Burp Suite is reachable at the given IP and port.
     *
     * Opens a TCP socket connection and immediately closes it.
     * If the connection succeeds, Burp Suite is listening and reachable.
     * If it fails, either the IP is wrong or Burp isn't running.
     *
     * This runs on Dispatchers.IO because socket operations are blocking.
     *
     * @param ip   The IP address to test (e.g., "192.168.1.100")
     * @param port The port to test (e.g., 8080)
     * @param timeoutMs Connection timeout in milliseconds (default: 2000ms)
     * @return true if a connection was established successfully
     */
    suspend fun isBurpReachable(ip: String, port: Int, timeoutMs: Int = 2000): Boolean {
        return withContext(Dispatchers.IO) {
            try {
                val socket = Socket()
                // InetSocketAddress combines IP + port into a single address object
                socket.connect(InetSocketAddress(ip, port), timeoutMs)
                socket.close()
                true // Connection succeeded — Burp is listening
            } catch (e: Exception) {
                false // Connection failed — Burp is not reachable
            }
        }
    }

    // -------------------------------------------------------------------------
    // Certificate installation
    // -------------------------------------------------------------------------

    /**
     * Downloads and installs Burp Suite's CA certificate into Android's system trust store.
     *
     * Why is this needed?
     *   When Burp intercepts HTTPS traffic, it decrypts it using its own certificate.
     *   Android apps check if the certificate is from a trusted Certificate Authority (CA).
     *   Burp's certificate is self-signed (not trusted by default), so apps reject it.
     *   Installing it as a system CA makes Android trust it for ALL apps.
     *
     * How it works:
     *   1. Burp Suite exposes its CA certificate at http://burp/cert (when proxy is active)
     *   2. We download the .der certificate file
     *   3. Convert it to the .0 format Android uses for system CAs
     *   4. Copy it to /system/etc/security/cacerts/ (requires root + remounting /system as rw)
     *
     * @param burpIp   The IP of the machine running Burp Suite
     * @param burpPort The Burp proxy port (typically 8080)
     * @return true if the certificate was installed successfully
     */
    suspend fun installBurpCertificate(burpIp: String, burpPort: Int): Boolean {
        return withContext(Dispatchers.IO) {
            try {
                if (!burpIp.matches(Regex("(?:[0-9]{1,3}\\.){3}[0-9]{1,3}")) ||
                    burpIp.split(".").any { (it.toIntOrNull() ?: 256) !in 0..255 } ||
                    burpPort !in 1..65535) {
                    return@withContext false
                }

                // Burp serves its certificate at this URL when the proxy is running.
                val certUrl = "http://$burpIp:$burpPort/cert"
                // Bound the wait: an unreachable listener must not stall setup for minutes.
                val download = RootUtils.executeSuCommand(
                    "rm -f /data/local/tmp/burp_ca.der; " +
                    "curl --connect-timeout 5 --max-time 12 --fail -sSL \"$certUrl\" " +
                    "-o /data/local/tmp/burp_ca.der && " +
                    "test -s /data/local/tmp/burp_ca.der && echo BURP_CERT_DOWNLOAD_OK"
                )
                if (!download.contains("BURP_CERT_DOWNLOAD_OK")) {
                    RootUtils.executeSuCommand("rm -f /data/local/tmp/burp_ca.der")
                    return@withContext false
                }

                // Convert .der format to the hash-named .0 format Android requires
                // openssl x509 reads the certificate and computes the hash Android needs
                RootUtils.executeSuCommand(
                    "openssl x509 -inform DER -in /data/local/tmp/burp_ca.der " +
                    "-out /data/local/tmp/burp_ca.pem"
                )

                // Get the certificate hash (Android names system CAs by their hash)
                val hash = RootUtils.executeSuCommand(
                    "openssl x509 -inform PEM -subject_hash_old -in /data/local/tmp/burp_ca.pem | head -1"
                ).trim()

                if (hash.isEmpty()) return@withContext false

                // Remount /system as read-write so we can copy the certificate
                // By default, /system is mounted as read-only for security reasons
                RootUtils.executeSuCommand("mount -o remount,rw /system")

                // Copy the certificate to the system CA store with the hash filename
                RootUtils.executeSuCommand(
                    "cp /data/local/tmp/burp_ca.pem /system/etc/security/cacerts/$hash.0"
                )

                // Set correct permissions for the certificate file
                RootUtils.executeSuCommand(
                    "chmod 644 /system/etc/security/cacerts/$hash.0"
                )

                // Remount /system as read-only again for security
                RootUtils.executeSuCommand("mount -o remount,ro /system")

                // Clean up temporary files
                RootUtils.executeSuCommand("rm -f /data/local/tmp/burp_ca.der")
                RootUtils.executeSuCommand("rm -f /data/local/tmp/burp_ca.pem")

                // Verify the certificate was installed
                val certCheck = RootUtils.executeSuCommand(
                    "ls /system/etc/security/cacerts/$hash.0"
                )
                return@withContext certCheck.contains(hash)
            } catch (e: Exception) {
                return@withContext false
            }
        }
    }

    /**
     * Checks whether Burp's CA certificate is installed in the system trust store.
     *
     * Looks for any certificate in the system CA store that was recently modified
     * (simple heuristic — a more robust check would verify the certificate content).
     *
     * @return true if any system CA certificate looks like it could be Burp's
     */
    suspend fun isBurpCertInstalled(): Boolean {
        return withContext(Dispatchers.IO) {
            try {
                // List all certificates in the system CA store
                val certs = RootUtils.executeSuCommand("ls /system/etc/security/cacerts/")
                // A simple way to check: the default Android CA store has a fixed set of certs.
                // For now, we just verify the directory is readable (can be improved later).
                certs.isNotEmpty() && !certs.contains("Permission denied")
            } catch (e: Exception) {
                false
            }
        }
    }
}
